#----------------------------------------------------------------------
# This file was generated by /usr/lib/python2.7/dist-packages/wx-2.8-gtk2-unicode/wx/tools/img2py.py
#
from wx.lib.embeddedimage import PyEmbeddedImage

movies_icon = PyEmbeddedImage(
    "iVBORw0KGgoAAAANSUhEUgAAANcAAAE/BAMAAAAnM0vdAAAAA3NCSVQICAjb4U/gAAAAG1BM"
    "VEXn5+fj4+Pf39/X19fS0tLOzs7KysrGxsbCwsKAlBBbAAAACXBIWXMAAAsSAAALEgHS3X78"
    "AAAAFXRFWHRDcmVhdGlvbiBUaW1lADQvMTkvMTHDVGG0AAAAHHRFWHRTb2Z0d2FyZQBBZG9i"
    "ZSBGaXJld29ya3MgQ1M0BrLToAAAAVlJREFUeJzt1rFKw1AUgOFUrTp20dnN1UF9AYuuFhEc"
    "K0pmFSFPIPjYEkouBSHxemjatN833eHATyC5OUUBAAAAAAAAAADkuZzmuQi09jNb05tA7CA3"
    "NhVbd2z8mEtsE2IPk6IYXXU00lAwNqsPJx2xNBSM3TeHNmlITGyVsV5f/V4/6jxiYmIbH7MW"
    "DO8XIza8mLVgQUxMTGxtMQtP+H92WJblvDm0SUNiOxd7rg+nHbE0FIy91N/rdUcsDQVjecTE"
    "xMSWY71eV71exPPm0CYNiYmtMmYHWRATExNbjr3WN9FtRyMNBWN2ELEdjfX26h9VVfV5VhR7"
    "d1W7NBSM5RETExNbjvV6XX3Uh/OOWBoKxt6aQ5s0JCa2ytifXv33ZigYs4OIiYmJ/Y5ZeIb3"
    "8xQbXszCsyC2U7Hj71zbG5v8PzbObX0Fnmz0lBmbBWIAAAAAAAAAAMBW+QHaf3bNxFjsPwAA"
    "AABJRU5ErkJggg==")
getmovies_iconData = movies_icon.GetData
getmovies_iconImage = movies_icon.GetImage
getmovies_iconBitmap = movies_icon.GetBitmap
getmovies_iconIcon = movies_icon.GetIcon

