# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'gui.ui'
#
# Created by: PyQt5 UI code generator 5.5.1
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1162, 679)
        font = QtGui.QFont()
        font.setFamily("Droid Sans [unknown]")
        MainWindow.setFont(font)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(90, 0, 91, 41))
        self.label.setStyleSheet("QLabel{\n"
"rgb(131, 131, 131);\n"
"font: 11pt \"Serif\";}")
        self.label.setTextFormat(QtCore.Qt.RichText)
        self.label.setObjectName("label")
        self.labelMov = QtWidgets.QLabel(self.centralwidget)
        self.labelMov.setGeometry(QtCore.QRect(420, 0, 381, 31))
        self.labelMov.setBaseSize(QtCore.QSize(0, 0))
        self.labelMov.setTextFormat(QtCore.Qt.RichText)
        self.labelMov.setAlignment(QtCore.Qt.AlignCenter)
        self.labelMov.setObjectName("labelMov")
        self.labelGenre = QtWidgets.QLabel(self.centralwidget)
        self.labelGenre.setGeometry(QtCore.QRect(290, 230, 241, 31))
        self.labelGenre.setTextFormat(QtCore.Qt.RichText)
        self.labelGenre.setAlignment(QtCore.Qt.AlignCenter)
        self.labelGenre.setObjectName("labelGenre")
        self.label_6 = QtWidgets.QLabel(self.centralwidget)
        self.label_6.setGeometry(QtCore.QRect(990, 20, 81, 21))
        self.label_6.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.label_6.setTextFormat(QtCore.Qt.RichText)
        self.label_6.setObjectName("label_6")
        self.textIMDBRating = QtWidgets.QTextBrowser(self.centralwidget)
        self.textIMDBRating.setGeometry(QtCore.QRect(400, 280, 41, 31))
        self.textIMDBRating.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.textIMDBRating.setObjectName("textIMDBRating")
        self.textRTRating = QtWidgets.QTextBrowser(self.centralwidget)
        self.textRTRating.setGeometry(QtCore.QRect(400, 330, 41, 31))
        self.textRTRating.setObjectName("textRTRating")
        self.textVoteCount = QtWidgets.QTextBrowser(self.centralwidget)
        self.textVoteCount.setGeometry(QtCore.QRect(970, 40, 111, 31))
        self.textVoteCount.setObjectName("textVoteCount")
        self.textDirector = QtWidgets.QTextBrowser(self.centralwidget)
        self.textDirector.setGeometry(QtCore.QRect(930, 380, 191, 31))
        self.textDirector.setObjectName("textDirector")
        self.textProducer = QtWidgets.QTextBrowser(self.centralwidget)
        self.textProducer.setGeometry(QtCore.QRect(930, 260, 191, 81))
        self.textProducer.setObjectName("textProducer")
        self.textStarCast = QtWidgets.QTextBrowser(self.centralwidget)
        self.textStarCast.setGeometry(QtCore.QRect(930, 100, 191, 131))
        self.textStarCast.setObjectName("textStarCast")
        self.label_7 = QtWidgets.QLabel(self.centralwidget)
        self.label_7.setGeometry(QtCore.QRect(1000, 360, 58, 16))
        self.label_7.setTextFormat(QtCore.Qt.RichText)
        self.label_7.setObjectName("label_7")
        self.label_8 = QtWidgets.QLabel(self.centralwidget)
        self.label_8.setGeometry(QtCore.QRect(1000, 80, 62, 16))
        self.label_8.setTextFormat(QtCore.Qt.RichText)
        self.label_8.setObjectName("label_8")
        self.label_9 = QtWidgets.QLabel(self.centralwidget)
        self.label_9.setGeometry(QtCore.QRect(1000, 240, 61, 16))
        self.label_9.setTextFormat(QtCore.Qt.RichText)
        self.label_9.setObjectName("label_9")
        self.textMovSummary = QtWidgets.QTextBrowser(self.centralwidget)
        self.textMovSummary.setGeometry(QtCore.QRect(550, 30, 341, 192))
        self.textMovSummary.setObjectName("textMovSummary")
        self.listWidget = QtWidgets.QListWidget(self.centralwidget)
        self.listWidget.setGeometry(QtCore.QRect(10, 30, 271, 271))
        self.listWidget.setObjectName("listWidget")
        self.horizontalLayoutWidget = QtWidgets.QWidget(self.centralwidget)
        self.horizontalLayoutWidget.setGeometry(QtCore.QRect(330, 30, 160, 191))
        self.horizontalLayoutWidget.setObjectName("horizontalLayoutWidget")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.horizontalLayoutWidget)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.imgLabel = QtWidgets.QLabel(self.horizontalLayoutWidget)
        self.imgLabel.setText("")
        self.imgLabel.setObjectName("imgLabel")
        self.horizontalLayout.addWidget(self.imgLabel)
        self.review1 = QtWidgets.QPushButton(self.centralwidget)
        self.review1.setGeometry(QtCore.QRect(320, 380, 141, 41))
        self.review1.setObjectName("review1")
        self.recommendButton = QtWidgets.QPushButton(self.centralwidget)
        self.recommendButton.setGeometry(QtCore.QRect(70, 310, 131, 31))
        self.recommendButton.setObjectName("recommendButton")
        self.listWidgetRecommend = QtWidgets.QListWidget(self.centralwidget)
        self.listWidgetRecommend.setGeometry(QtCore.QRect(10, 350, 271, 231))
        self.listWidgetRecommend.setObjectName("listWidgetRecommend")
        self.horizontalLayoutWidget_2 = QtWidgets.QWidget(self.centralwidget)
        self.horizontalLayoutWidget_2.setGeometry(QtCore.QRect(550, 250, 341, 191))
        self.horizontalLayoutWidget_2.setObjectName("horizontalLayoutWidget_2")
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout(self.horizontalLayoutWidget_2)
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.wordCloudLabel = QtWidgets.QLabel(self.horizontalLayoutWidget_2)
        self.wordCloudLabel.setText("")
        self.wordCloudLabel.setObjectName("wordCloudLabel")
        self.horizontalLayout_3.addWidget(self.wordCloudLabel)
        self.horizontalLayoutWidget_3 = QtWidgets.QWidget(self.centralwidget)
        self.horizontalLayoutWidget_3.setGeometry(QtCore.QRect(300, 470, 614, 111))
        self.horizontalLayoutWidget_3.setObjectName("horizontalLayoutWidget_3")
        self.gridLayout = QtWidgets.QGridLayout(self.horizontalLayoutWidget_3)
        self.gridLayout.setObjectName("gridLayout")
        self.pbarSad = QtWidgets.QProgressBar(self.horizontalLayoutWidget_3)
        self.pbarSad.setProperty("value", 24)
        self.pbarSad.setObjectName("pbarSad")
        self.gridLayout.addWidget(self.pbarSad, 1, 2, 1, 1)
        self.pbarFear = QtWidgets.QProgressBar(self.horizontalLayoutWidget_3)
        self.pbarFear.setProperty("value", 24)
        self.pbarFear.setObjectName("pbarFear")
        self.gridLayout.addWidget(self.pbarFear, 1, 4, 1, 1)
        self.pbarAngry = QtWidgets.QProgressBar(self.horizontalLayoutWidget_3)
        self.pbarAngry.setProperty("value", 24)
        self.pbarAngry.setObjectName("pbarAngry")
        self.gridLayout.addWidget(self.pbarAngry, 1, 3, 1, 1)
        self.pbarSurprise = QtWidgets.QProgressBar(self.horizontalLayoutWidget_3)
        self.pbarSurprise.setProperty("value", 24)
        self.pbarSurprise.setObjectName("pbarSurprise")
        self.gridLayout.addWidget(self.pbarSurprise, 1, 1, 1, 1)
        self.label_3 = QtWidgets.QLabel(self.horizontalLayoutWidget_3)
        self.label_3.setText("")
        self.label_3.setPixmap(QtGui.QPixmap("images/Joy.png"))
        self.label_3.setAlignment(QtCore.Qt.AlignCenter)
        self.label_3.setObjectName("label_3")
        self.gridLayout.addWidget(self.label_3, 0, 0, 1, 1)
        self.pbarHappy = QtWidgets.QProgressBar(self.horizontalLayoutWidget_3)
        self.pbarHappy.setProperty("value", 24)
        self.pbarHappy.setObjectName("pbarHappy")
        self.gridLayout.addWidget(self.pbarHappy, 1, 0, 1, 1)
        self.label_11 = QtWidgets.QLabel(self.horizontalLayoutWidget_3)
        self.label_11.setText("")
        self.label_11.setPixmap(QtGui.QPixmap("images/Surprised.png"))
        self.label_11.setAlignment(QtCore.Qt.AlignCenter)
        self.label_11.setObjectName("label_11")
        self.gridLayout.addWidget(self.label_11, 0, 1, 1, 1)
        self.label_2 = QtWidgets.QLabel(self.horizontalLayoutWidget_3)
        self.label_2.setText("")
        self.label_2.setPixmap(QtGui.QPixmap("images/Angry.png"))
        self.label_2.setAlignment(QtCore.Qt.AlignCenter)
        self.label_2.setObjectName("label_2")
        self.gridLayout.addWidget(self.label_2, 0, 3, 1, 1)
        self.label_12 = QtWidgets.QLabel(self.horizontalLayoutWidget_3)
        self.label_12.setText("")
        self.label_12.setPixmap(QtGui.QPixmap("images/Sad.png"))
        self.label_12.setAlignment(QtCore.Qt.AlignCenter)
        self.label_12.setObjectName("label_12")
        self.gridLayout.addWidget(self.label_12, 0, 2, 1, 1)
        self.label_13 = QtWidgets.QLabel(self.horizontalLayoutWidget_3)
        self.label_13.setText("")
        self.label_13.setPixmap(QtGui.QPixmap("images/Fear.png"))
        self.label_13.setAlignment(QtCore.Qt.AlignCenter)
        self.label_13.setObjectName("label_13")
        self.gridLayout.addWidget(self.label_13, 0, 4, 1, 1)
        self.progressBar = QtWidgets.QProgressBar(self.centralwidget)
        self.progressBar.setGeometry(QtCore.QRect(960, 520, 141, 20))
        self.progressBar.setProperty("value", 24)
        self.progressBar.setObjectName("progressBar")
        self.progressInfo = QtWidgets.QLabel(self.centralwidget)
        self.progressInfo.setGeometry(QtCore.QRect(1000, 500, 67, 17))
        self.progressInfo.setTextFormat(QtCore.Qt.PlainText)
        self.progressInfo.setObjectName("progressInfo")
        self.label_10 = QtWidgets.QLabel(self.centralwidget)
        self.label_10.setGeometry(QtCore.QRect(330, 280, 61, 31))
        self.label_10.setText("")
        self.label_10.setPixmap(QtGui.QPixmap("images/imdb.jpg"))
        self.label_10.setAlignment(QtCore.Qt.AlignCenter)
        self.label_10.setObjectName("label_10")
        self.label_14 = QtWidgets.QLabel(self.centralwidget)
        self.label_14.setGeometry(QtCore.QRect(340, 330, 31, 31))
        self.label_14.setText("")
        self.label_14.setPixmap(QtGui.QPixmap("images/rt.png"))
        self.label_14.setScaledContents(True)
        self.label_14.setAlignment(QtCore.Qt.AlignCenter)
        self.label_14.setObjectName("label_14")
        self.label.raise_()
        self.labelMov.raise_()
        self.labelGenre.raise_()
        self.label_6.raise_()
        self.textIMDBRating.raise_()
        self.textRTRating.raise_()
        self.textVoteCount.raise_()
        self.textDirector.raise_()
        self.textProducer.raise_()
        self.textStarCast.raise_()
        self.label_7.raise_()
        self.label_8.raise_()
        self.label_9.raise_()
        self.textMovSummary.raise_()
        self.listWidget.raise_()
        self.horizontalLayoutWidget.raise_()
        self.review1.raise_()
        self.recommendButton.raise_()
        self.listWidgetRecommend.raise_()
        self.horizontalLayoutWidget_2.raise_()
        self.horizontalLayoutWidget_3.raise_()
        self.progressBar.raise_()
        self.progressInfo.raise_()
        self.label_14.raise_()
        self.label_10.raise_()
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1162, 26))
        self.menubar.setObjectName("menubar")
        self.menuFile = QtWidgets.QMenu(self.menubar)
        self.menuFile.setObjectName("menuFile")
        self.menuOptions = QtWidgets.QMenu(self.menubar)
        self.menuOptions.setObjectName("menuOptions")
        self.menuAbout = QtWidgets.QMenu(self.menubar)
        self.menuAbout.setObjectName("menuAbout")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)
        self.actionAdd_Files = QtWidgets.QAction(MainWindow)
        self.actionAdd_Files.setObjectName("actionAdd_Files")
        self.actionAdd_Folders = QtWidgets.QAction(MainWindow)
        self.actionAdd_Folders.setObjectName("actionAdd_Folders")
        self.actionOptions = QtWidgets.QAction(MainWindow)
        self.actionOptions.setObjectName("actionOptions")
        self.actionHelp = QtWidgets.QAction(MainWindow)
        self.actionHelp.setObjectName("actionHelp")
        self.actionVersion = QtWidgets.QAction(MainWindow)
        self.actionVersion.setObjectName("actionVersion")
        self.actionExit = QtWidgets.QAction(MainWindow)
        self.actionExit.setObjectName("actionExit")
        self.actionSync = QtWidgets.QAction(MainWindow)
        self.actionSync.setObjectName("actionSync")
        self.menuFile.addAction(self.actionAdd_Files)
        self.menuFile.addAction(self.actionAdd_Folders)
        self.menuFile.addAction(self.actionSync)
        self.menuFile.addAction(self.actionExit)
        self.menuOptions.addAction(self.actionOptions)
        self.menuAbout.addAction(self.actionHelp)
        self.menuAbout.addAction(self.actionVersion)
        self.menubar.addAction(self.menuFile.menuAction())
        self.menubar.addAction(self.menuOptions.menuAction())
        self.menubar.addAction(self.menuAbout.menuAction())

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.label.setText(_translate("MainWindow", "Video Listing"))
        self.labelMov.setText(_translate("MainWindow", "Movie Name & Year"))
        self.labelGenre.setText(_translate("MainWindow", "Genre"))
        self.label_6.setText(_translate("MainWindow", "Vote Count"))
        self.label_7.setText(_translate("MainWindow", "Director"))
        self.label_8.setText(_translate("MainWindow", "Starcast"))
        self.label_9.setText(_translate("MainWindow", "Producer"))
        self.review1.setText(_translate("MainWindow", "Review"))
        self.recommendButton.setText(_translate("MainWindow", "Recommend"))
        self.progressInfo.setText(_translate("MainWindow", "TextLabel"))
        self.menuFile.setTitle(_translate("MainWindow", "File"))
        self.menuOptions.setTitle(_translate("MainWindow", "Tools"))
        self.menuAbout.setTitle(_translate("MainWindow", "About"))
        self.actionAdd_Files.setText(_translate("MainWindow", "Add Files"))
        self.actionAdd_Folders.setText(_translate("MainWindow", "Add Folders"))
        self.actionOptions.setText(_translate("MainWindow", "Preferences"))
        self.actionHelp.setText(_translate("MainWindow", "Help"))
        self.actionVersion.setText(_translate("MainWindow", "Version"))
        self.actionExit.setText(_translate("MainWindow", "Exit"))
        self.actionSync.setText(_translate("MainWindow", "Sync"))

